name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/MemphisNguyen/esc_pos_printer
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils:
    git:
      url: https://github.com/MemphisNguyen/esc_pos_utils/
  flutter:
    sdk: flutter
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
